server:
  port: 8454
logging:
  file: /java/C2S_LOGS/context-handler/context-handler.log
info:
  component: Context Handler API
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/pcm?autoReconnect=true
    username: root
    password: admin
c2s:
  context-handler:
    policy-provider: PcmServicePolicyProviderImpl
    pid:
      type: ISO
    polrep:
      policySet:
        combiningAlgs:
          first-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:first-applicable
          ordered-deny-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-deny-overrides
          ordered-permit-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-permit-overrides
          deny-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:deny-overrides
          only-one-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:only-one-applicable
          permit-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:permit-overrides
    pdpRequest:
      resource:
        typeCode: 34133-9
        status: urn:oasis:names:tc:ebxml-regrep:StatusType:Approved
    audit-client:
      enabled: false
      host: localhost
      port: 9630
    fhir:
      enabled: false
      # configure fhir server base url
      serverUrl: http://bhitsdevhie01/hapi-fhir-jpaserver/baseDstu3
      clientSocketTimeoutInMs: 768000
      ssn:
        system: http://hl7.org/fhir/sid/us-ssn
        oid: urn:oid:2.16.840.1.113883.4.1
        label: SSN
      npi:
        system: http://hl7.org/fhir/sid/us-npi
        oid: urn:oid:2.16.840.1.113883.4.6
        label: PRN
      pou:
        system: http://hl7.org/fhir/v3/ActReason
        oid: urn:oid:2.16.840.1.113883.1.11.20448
        label: PurposeOfUse
      mrn:
        system: https://bhits.github.io/consent2share
        oid: urn:oid:1.3.6.1.4.1.21367.13.20.200
        label: MRN
---
# enables ssl and adds /contextHandler context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server.context-path: /contextHandler
---
# updates configuration for docker environment
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://${C2S_DB_HOST:pcm-db.c2s.com}:${C2S_DB_PORT:3306}/pcm?autoReconnect=true
c2s:
  context-handler:
    audit-client:
      host: logback-audit-server.c2s.com
    fhir:
      serverUrl: http://hapi-fhir.c2s.com:8080/hapi-fhir-jpaserver/baseDstu3